name: update-submodule

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Checkout submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit & Update submodules
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references by .github/update-submodule.yml" && git push || echo "No changes to commit"
